# Synthetic Cat Species: Generation & Multi-Strategy Classification

This repository documents the end-to-end development of a synthetic computer vision pipeline, covering **latent diffusion generation**, **custom architecture design**, and a benchmark of **modern learning paradigms**.

---

## 🛠 Project Workflow

### 1. Data Synthesis (`dataset_generation.ipynb`)
I used **Stable Diffusion** to build a custom dataset from scratch. By engineering prompts for specific cat species, I generated a balanced, labeled image library. This served as the primary data source for all subsequent experiments.

### 2. Deep Learning Experiments

#### **Custom Architecture** (`CustomCNN.ipynb`)
* **Design:** A bespoke CNN featuring **Residual blocks** and **Attention mechanisms**.
* **Goal:** Establish a baseline for training on synthetic data without prior weights.
* **Result:** **20.24% Accuracy**. This highlights the difficulty of learning fine-grained features from scratch on small synthetic sets.

#### **Transfer Learning & Inference** (`resnet_inference_accuracy.ipynb`)
* **Zero-Shot:** Using a pre-trained **ResNet-18** for direct inference via semantic label matching. (**94.05% Accuracy**)
* **Few-Shot:** Adapting the model using only a handful of examples per category. (**72.62% Accuracy**)
* **Continual Learning:** Testing the model's ability to learn species incrementally over time. (**66.67% Accuracy**)
* **Full Fine-Tuning:** Re-training the ResNet backbone on the generated dataset. (**87% Accuracy**)

---

## 📊 Performance Benchmark

| Methodology | Accuracy |
| :--- | :--- |
| **Zero-Shot (ResNet)** | 94.05% |
| **Full Fine-Tuned ResNet** | 87.00% |
| **Few-Shot Learning** | 72.62% |
| **Continual Learning** | 66.67% |
| **Custom CNN (Baseline)** | 20.24% |

---

## 💡 Key Takeaways
* **Pre-trained Superiority:** Models with existing weight distributions (ResNet) vastly outperform custom models built from scratch for this task.
* **Synthetic Quality:** The high Zero-Shot accuracy proves the synthetic images generated by Stable Diffusion are high-quality enough to be recognized by models trained on real-world data.
* **Stability Issues:** The drop in accuracy during Continual Learning illustrates the challenge of "forgetting" when introducing new species sequentially.

---

## 🖥️ Tech Stack
* **Generation:** Stable Diffusion (Hugging Face)
* **Modeling:** PyTorch
* **Hardware:** Optimized for **RTX 4060 GPU** (Asus TUF)
